name: Cubefree
version: "1.21"
license: "GPL-2.0-or-later"
date: 2025-08-29
description: |
    Constructing the Groups of a Given Cubefree Order

authors:
    - name: Heiko Dietrich
      url: http://users.monash.edu.au/~heikod/

maintainers:
    - name: Heiko Dietrich
      url: http://users.monash.edu.au/~heikod/

GAP: ">=4.9"

needed-pkgs:
    - name: "GrpConst"
      version: "2.5"
      url: "https://gap-packages.github.io/grpconst/"
    - name: "Polycyclic"
      version: "2.11"
      url: "https://gap-packages.github.io/polycyclic/"
    - name: "smallgrp"
      version: "1.3"
      url: "https://gap-packages.github.io/smallgrp/"

www: https://gap-packages.github.io/cubefree/
readme: README.md
packageinfo: https://gap-packages.github.io/cubefree/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/cubefree/releases/download/v1.21/cubefree-1.21.tar.gz

abstract: |
    The <span class="pkgname">Cubefree</span> package contains methods to construct up to isomorphism the groups of a given (reasonable) cubefree order. The main function ConstructAllCFGroups(n) constructs all groups of a given cubefree order n. The function NumberCFGroups(n) counts all groups of a cubefree order n. Furthermore, IrreducibleSubgroupsOfGL(2,q) constructs the irreducible subgroups of GL(2,q), q=p^r, p>=5 prime, up to conjugacy and RewriteAbsolutelyIrreducibleMatrixGroup(G) rewrites the absolutely irreducible matrix group G (over a finite field) over a minimal subfield.

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
keywords: |
    cubefree, construction of groups, irreducible matrix subgroups of degree 2.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Die25</span>]   <b class='BibAuthor'>Dietrich, H.</b>,
     <i class='BibTitle'>Cubefree, Constructing the Groups of a Given Cubefree Order,
             Version 1.21</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/cubefree/">https://gap-packages.github.io/cubefree/</a></span>.
    </p>
    

bibtex: |
    @misc{ Cubefree,
      author =           {Dietrich, H.},
      title =            {{Cubefree},   {Constructing  the  Groups  of  a  Given
                          Cubefree Order}, {V}ersion 1.21},
      month =            {Aug},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href       {https://gap-packages.github.io/cubefree/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{cubefree/}}},
      keywords =         {cubefree;  construction  of groups; irreducible matrix
                          subgroups of degree 2},
      printedkey =       {Die25}
    }

